# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 496ea70e0ef13e0f6ddfa668177f6916ee0eacfb194ef1805596d59eb84cd1023e348904fff04a49b28b8c7bc07c92e4dbc9ee832f4e1a75faba2732a3537036

test:
  secret_key_base: 0c57066df022df3e3d60ca209fd5590e0169aa4584e2321bceea5de2a7af21116eeb6d2b1f4db8433d4d64765283120b858a776d4dc1bd0fa9ebf2527cb59615

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
